from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time

# https://discord.gg/XqMnKuTy
sleepTime = 1.5

PATH = 'chromedriver'
driver = webdriver.Chrome(PATH)
driver.get('https://discord.com')
time.sleep(9)
# check = driver.find_elements_by_id('terms-checkbox')
# check.click()
# time.sleep(2)
login = driver.switch_to_active_element()
login.send_keys('ronny')
login.send_keys(Keys.RETURN)
time.sleep(5)
age = driver.switch_to_active_element()
age.send_keys(1)
age.send_keys(Keys.RETURN)
age.send_keys(Keys.TAB)
age.send_keys(Keys.TAB)
age = driver.switch_to_active_element()
age.send_keys(1)
age.send_keys(Keys.RETURN)
age.send_keys(Keys.TAB)
age.send_keys(Keys.TAB)
age = driver.switch_to_active_element()
age.send_keys(1978)
age.send_keys(Keys.RETURN)
age.send_keys(Keys.TAB)
age.send_keys(Keys.TAB)
age = driver.switch_to_active_element()
age.send_keys(Keys.RETURN)
time.sleep(5)
# TBD
# driver.find_elements_by_class_name('joinCTA-1s7TZx').click()
# age.send_keys(Keys.RETURN)
# age.send_keys(Keys.TAB)
# age.send_keys(Keys.TAB)
# age = driver.switch_to_active_element()
# age.send_keys(Keys.RETURN)
# age.send_keys(Keys.TAB)
# age.send_keys(Keys.TAB)
# age = driver.switch_to_active_element()
# age.send_keys(Keys.RETURN)
# age.send_keys(Keys.TAB)
# age.send_keys(Keys.TAB)
# age = driver.switch_to_active_element()
# age.send_keys(Keys.RETURN)
# age.send_keys(Keys.TAB)
# age.send_keys(Keys.TAB)
# age = driver.switch_to_active_element()
# age.send_keys(Keys.RETURN)
# age.send_keys(Keys.TAB)
# age.send_keys(Keys.TAB)
# age = driver.switch_to_active_element()
# age.send_keys(Keys.RETURN)
# age.send_keys(Keys.TAB)
# age.send_keys(Keys.TAB)
# age = driver.switch_to_active_element()
# age.send_keys(Keys.RETURN)
# age.send_keys(Keys.TAB)
# age.send_keys(Keys.TAB)
# age = driver.switch_to_active_element()
# age.send_keys(Keys.RETURN)
time.sleep(35)
print('35 sec over')
time.sleep(10)
print('45 sec over')
# try:
#     dc = WebDriverWait(driver, 10).until(
#         EC.presence_of_element_located((By.ID, 'button-195cDm buttonDark-1kG4vN buttonLarge-2j8B-n gtm-click-class-open-button openButton-McADyK'))
#     )
#     dc.click()
# except:
#     quit()
message = driver.switch_to_active_element()
message.click()
message.send_keys('rpg start')
message.send_keys(Keys.RETURN)
time.sleep(sleepTime)
message.send_keys('rpg hunt')
message.send_keys(Keys.RETURN)
time.sleep(sleepTime)
message.send_keys('rpg adv')
message.send_keys(Keys.RETURN)
time.sleep(sleepTime)
message.send_keys('rpg daily')
message.send_keys(Keys.RETURN)
time.sleep(sleepTime)
message.send_keys('rpg weekly')
message.send_keys(Keys.RETURN)
time.sleep(sleepTime)
message.send_keys('rpg open')
message.send_keys(Keys.RETURN)
time.sleep(sleepTime)
message.send_keys('rpg code code')
message.send_keys(Keys.RETURN)
time.sleep(sleepTime)
message.send_keys('rpg code epicrpg')
message.send_keys(Keys.RETURN)
time.sleep(sleepTime)
message.send_keys('rpg code epicrpgxmas')
message.send_keys(Keys.RETURN)
time.sleep(sleepTime)
message.send_keys('rpg code lmao')
message.send_keys(Keys.RETURN)
time.sleep(sleepTime)
message.send_keys('rpg xmas open godly present')
message.send_keys(Keys.RETURN)
time.sleep(sleepTime)
message.send_keys('rpg xmas open epic present 5')
message.send_keys(Keys.RETURN)
time.sleep(sleepTime)


message.send_keys('rpg dismantle epic fish all')
message.send_keys(Keys.RETURN)
time.sleep(sleepTime)
message.send_keys('rpg dismantle golden fish all')
message.send_keys(Keys.RETURN)
time.sleep(sleepTime)
message.send_keys('rpg dismantle ultra log all')
message.send_keys(Keys.RETURN)
time.sleep(sleepTime)
message.send_keys('rpg dismantle hyper log all')
message.send_keys(Keys.RETURN)
time.sleep(sleepTime)
message.send_keys('rpg dismantle mega log all')
message.send_keys(Keys.RETURN)
time.sleep(sleepTime)
message.send_keys('rpg dismantle super log all')
message.send_keys(Keys.RETURN)
time.sleep(sleepTime)
message.send_keys('rpg dismantle epic log all')
message.send_keys(Keys.RETURN)
time.sleep(sleepTime)
message.send_keys('rpg trade a all')
message.send_keys(Keys.RETURN)
time.sleep(sleepTime)
message.send_keys('rpg sell wooden log all')
message.send_keys(Keys.RETURN)
time.sleep(sleepTime)
message.send_keys('rpg sell arena cookie all')
message.send_keys(Keys.RETURN)
time.sleep(sleepTime)

message.send_keys('rpg give 80k @Jim Knopf#9919')
message.send_keys(Keys.RETURN)
message.send_keys(Keys.TAB)
settings = driver.switch_to_active_element()
settings.send_keys(Keys.TAB)
settings = driver.switch_to_active_element()
settings.send_keys(Keys.TAB)
settings = driver.switch_to_active_element()
settings.send_keys(Keys.TAB)
settings = driver.switch_to_active_element()
settings.send_keys(Keys.TAB)
settings = driver.switch_to_active_element()
settings.send_keys(Keys.TAB)
settings = driver.switch_to_active_element()
settings.send_keys(Keys.TAB)
settings = driver.switch_to_active_element()
settings.send_keys(Keys.TAB)
settings = driver.switch_to_active_element()
settings.send_keys(Keys.TAB)
settings = driver.switch_to_active_element()
settings.send_keys(Keys.TAB)
settings = driver.switch_to_active_element()
settings.send_keys(Keys.TAB)
settings = driver.switch_to_active_element()
settings.send_keys(Keys.TAB)
settings = driver.switch_to_active_element()
settings.send_keys(Keys.TAB)
settings = driver.switch_to_active_element()
settings.send_keys(Keys.TAB)
settings = driver.switch_to_active_element()
settings.send_keys(Keys.TAB)
settings = driver.switch_to_active_element()
settings.send_keys(Keys.TAB)
settings = driver.switch_to_active_element()
settings.send_keys(Keys.TAB)
settings = driver.switch_to_active_element()
settings.send_keys(Keys.TAB)
settings = driver.switch_to_active_element()
settings.send_keys(Keys.RETURN)

time.sleep(10)
